### ISSUE TITLE
The server returned status code '522' when status code '101' was expected.

### ISSUE THREAD

**Issue by wraikny** [wraikny/WraindropBot#5]
```
[2022-06-21 15:32:58 +09:00] [110 /HeartbeatFai] [Crit ] Server failed to acknowledge more than 5 heartbeats - connection is zombie
[2022-06-21 15:33:39 +09:00] [110 /HeartbeatFai] [Crit ] Server failed to acknowledge more than 5 heartbeats - connection is zombie
[2022-06-21 15:34:20 +09:00] [110 /HeartbeatFai] [Crit ] Server failed to acknowledge more than 5 heartbeats - connection is zombie
[2022-06-21 15:35:02 +09:00] [110 /HeartbeatFai] [Crit ] Server failed to acknowledge more than 5 heartbeats - connection is zombie
[2022-06-21 15:35:43 +09:00] [110 /HeartbeatFai] [Crit ] Server failed to acknowledge more than 5 heartbeats - connection is zombie
[2022-06-21 15:36:18 +09:00] [111 /ConnectionCl] [Crit ] Connection terminated (-1, ''), reconnecting
[2022-06-21 15:36:18 +09:00] [101 /Startup     ] [Info ] DSharpPlus, version 4.2.0
[2022-06-21 15:37:20 +09:00] [102 /ConnectionFa] [Error] Connection attempt failed, retrying in 7s
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '522' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri , CancellationToken , ClientWebSocketOptions )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , CancellationToken )
   at DSharpPlus.Net.WebSocket.WebSocketClient.ConnectAsync(Uri uri)
   at DSharpPlus.DiscordClient.InternalConnectAsync()
   at DSharpPlus.DiscordClient.ConnectAsync(DiscordActivity activity, Nullable`1 status, Nullable`1 idlesince)
[2022-06-21 15:38:29 +09:00] [102 /ConnectionFa] [Error] Connection attempt failed, retrying in 15s
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '522' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri , CancellationToken , ClientWebSocketOptions )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , CancellationToken )
   at DSharpPlus.Net.WebSocket.WebSocketClient.ConnectAsync(Uri uri)
   at DSharpPlus.DiscordClient.InternalConnectAsync()
   at DSharpPlus.DiscordClient.ConnectAsync(DiscordActivity activity, Nullable`1 status, Nullable`1 idlesince)
[2022-06-21 15:39:46 +09:00] [102 /ConnectionFa] [Error] Connection attempt failed, retrying in 30s
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '522' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri , CancellationToken , ClientWebSocketOptions )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , CancellationToken )
   at DSharpPlus.Net.WebSocket.WebSocketClient.ConnectAsync(Uri uri)
   at DSharpPlus.DiscordClient.InternalConnectAsync()
   at DSharpPlus.DiscordClient.ConnectAsync(DiscordActivity activity, Nullable`1 status, Nullable`1 idlesince)
[2022-06-21 15:41:18 +09:00] [102 /ConnectionFa] [Error] Connection attempt failed, retrying in 60s
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '522' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri , CancellationToken , ClientWebSocketOptions )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , CancellationToken )
   at DSharpPlus.Net.WebSocket.WebSocketClient.ConnectAsync(Uri uri)
   at DSharpPlus.DiscordClient.InternalConnectAsync()
   at DSharpPlus.DiscordClient.ConnectAsync(DiscordActivity activity, Nullable`1 status, Nullable`1 idlesince)
```

**Comment by wraikny** [comment]
resolved by updating DSharpPlus
